[package]
authors.workspace      = true
description            = "A binary for running stress tests against the Miden node"
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "stress-test"]
license.workspace      = true
name                   = "miden-node-stress-test"
publish                = false
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
clap                      = { features = ["derive"], version = "4.5" }
fs-err                    = { workspace = true }
futures                   = { workspace = true }
miden-air                 = { features = ["testing"], workspace = true }
miden-block-prover        = { features = ["testing"], workspace = true }
miden-lib                 = { workspace = true }
miden-node-block-producer = { workspace = true }
miden-node-proto          = { workspace = true }
miden-node-store          = { workspace = true }
miden-node-utils          = { workspace = true }
miden-objects             = { workspace = true }
rand                      = { workspace = true }
rayon                     = { version = "1.10" }
tokio                     = { workspace = true }
tonic                     = { default-features = true, workspace = true }
url                       = { workspace = true }
