[package]
authors.workspace      = true
description            = "Miden network monitor"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "monitor", "network"]
license.workspace      = true
name                   = "miden-network-monitor"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow           = { workspace = true }
axum             = { version = "0.8" }
clap             = { features = ["env"], workspace = true }
humantime        = { workspace = true }
miden-lib        = { workspace = true }
miden-node-proto = { workspace = true }
miden-node-utils = { workspace = true }
miden-objects    = { features = ["std", "testing"], workspace = true }
miden-testing    = { workspace = true }
miden-tx         = { features = ["std"], workspace = true }
rand             = { version = "0.9" }
rand_chacha      = { version = "0.9" }
reqwest          = { features = ["json"], version = "0.12" }
serde            = { features = ["derive"], version = "1.0" }
serde_json       = { version = "1.0" }
sha2             = { version = "0.10" }
tokio            = { features = ["full"], workspace = true }
tonic            = { features = ["codegen", "tls-native-roots", "transport"], workspace = true }
tracing          = { workspace = true }
url              = { features = ["serde"], workspace = true }
