name: Publish (dry-run)

permissions:
  contents: read

on:
  push:
    branches: [main]

jobs:
  publish-dry-run:
    name: Cargo publish dry-run
    runs-on: Linux-ARM64-Runner
    if: ${{ github.repository_owner == '0xMiden' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Rust toolchain
        run: |
          rustup update --no-self-update
      - name: Run cargo publish dry-run
        run: cargo publish --workspace --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
