name: Publish (dry-run)

permissions:
  contents: read

on:
  push:
    branches: [main, next]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  publish-dry-run:
    name: Cargo publish dry-run
    runs-on: Linux-ARM64-Runner
    if: ${{ github.repository_owner == '0xMiden' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - name: Install RocksDB
        uses: ./.github/actions/install-rocksdb
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Update Rust toolchain
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall@1.16.6
      - name: Install cargo-msrv
        run: cargo binstall --no-confirm --force cargo-msrv
      - name: Check MSRV for each workspace member
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          ./scripts/check-msrv.sh
      - name: Run cargo publish dry-run
        run: cargo publish --workspace --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
